-- Module 2 confirmation profiles describe strategy evidence only.
-- Risk and confidence are evaluated after a profile is selected.
UPDATE module2_strategy_variants
SET required_rules = CASE code
      WHEN 'SWEEP_CLOSE_BACK_INSIDE' THEN '["LIQUIDITY_SWEEP_CONFIRMED","SWEEP_REJECTION_CONFIRMED"]'::jsonb
      WHEN 'SWEEP_BOS' THEN '["LIQUIDITY_SWEEP_CONFIRMED","SWEEP_REJECTION_CONFIRMED","CONTINUATION_BOS"]'::jsonb
      WHEN 'SWEEP_MSS' THEN '["LIQUIDITY_SWEEP_CONFIRMED","SWEEP_REJECTION_CONFIRMED","REVERSAL_MSS","MSS_STRENGTH"]'::jsonb
      WHEN 'SWEEP_ENGULFING' THEN '["LIQUIDITY_SWEEP_CONFIRMED","CONFIRM_ENGULFING"]'::jsonb
      WHEN 'SWEEP_BOS_RETEST' THEN '["LIQUIDITY_SWEEP_CONFIRMED","CONTINUATION_BOS","ENTRY_ZONE_RETRACE"]'::jsonb
      WHEN 'SWEEP_MSS_RETEST' THEN '["LIQUIDITY_SWEEP_CONFIRMED","SWEEP_REJECTION_CONFIRMED","REVERSAL_MSS","MSS_STRENGTH","ENTRY_ZONE_READY","ENTRY_ZONE_RETRACE","CONFIRM_ENTRY_CANDLE","DIRECTIONAL_CONFLICT_CLEAR"]'::jsonb
      WHEN 'SWEEP_EMA_ALIGNMENT' THEN '["LIQUIDITY_SWEEP_CONFIRMED","CONFIRM_EMA_200"]'::jsonb
      WHEN 'SWEEP_VOLUME_EXPANSION' THEN '["LIQUIDITY_SWEEP_CONFIRMED","CONFIRM_VOLUME_EXPANSION"]'::jsonb
      WHEN 'SWEEP_MSS_DISPLACEMENT_RETEST' THEN '["LIQUIDITY_SWEEP_CONFIRMED","REVERSAL_MSS","DISPLACEMENT_CONFIRMED","ENTRY_ZONE_RETRACE"]'::jsonb
      WHEN 'SWEEP_NO_CONFIRMATION' THEN '["LIQUIDITY_SWEEP_CONFIRMED"]'::jsonb
      ELSE required_rules
    END,
    updated_at = now()
WHERE module_code = 'high_probability_strategy_2';
